### ISSUE TITLE
回復原先的.app.background樣式

### ISSUE THREAD

**Issue by a8568730** [g0v/itaigi#343]
之前為了 #329 
在.app.background加樣式
```css
.app.background {
  ...
  width: 100vw;
  overflow-y: scroll;
  overflow-x: hidden;
}
```
這三行發現無用
